// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvlO1FEmP5D91FFpjMIZYKa75WZ_U2Zx8',
    appId: '1:1034774400320:web:b8a69654ff0d2078c43ea5',
    messagingSenderId: '1034774400320',
    projectId: 'noti-7932a',
    authDomain: 'noti-7932a.firebaseapp.com',
    storageBucket: 'noti-7932a.firebasestorage.app',
    measurementId: 'G-E8RL4E6J2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRAgU_K7Zykyk_4cbIFPczWQJtpxwl12U',
    appId: '1:1034774400320:android:b7dedc76f863f72bc43ea5',
    messagingSenderId: '1034774400320',
    projectId: 'noti-7932a',
    storageBucket: 'noti-7932a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxIs8MXY31Ik4uNkLkuRqBQ39QCmhvcbw',
    appId: '1:1034774400320:ios:bf595bc49437d468c43ea5',
    messagingSenderId: '1034774400320',
    projectId: 'noti-7932a',
    storageBucket: 'noti-7932a.firebasestorage.app',
    iosBundleId: 'com.example.notify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxIs8MXY31Ik4uNkLkuRqBQ39QCmhvcbw',
    appId: '1:1034774400320:ios:bf595bc49437d468c43ea5',
    messagingSenderId: '1034774400320',
    projectId: 'noti-7932a',
    storageBucket: 'noti-7932a.firebasestorage.app',
    iosBundleId: 'com.example.notify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvlO1FEmP5D91FFpjMIZYKa75WZ_U2Zx8',
    appId: '1:1034774400320:web:ebe164a3b275f1efc43ea5',
    messagingSenderId: '1034774400320',
    projectId: 'noti-7932a',
    authDomain: 'noti-7932a.firebaseapp.com',
    storageBucket: 'noti-7932a.firebasestorage.app',
    measurementId: 'G-K8RWX7Z3TL',
  );
}
